### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by pelletier197** [markedjs/marked-gfm-heading-id#315]
## Issue 
This module does not seem to provide typescript definitions. This causes compile errors in the projects using `TypeScript + marked`.

Do you think  it be possible to provide these either out of the box or through `@types/marked-gfm-heading-id`?

**Comment by pelletier197** [comment]
I took the time to write it for my project. Something like this should do the trick

```typescript
declare module 'marked-gfm-heading-id' {
  type Extension = {
    hooks: {
      preprocess: (markdown: string) => string
    }
    renderer: {
      heading: (text: string, level: number, raw: string) => string
    }
  }

  export type Parameters = {
    prefix?: string
  }

  export const gfmHeadingId: (params?: Parameters) => Extension
}

```

**Comment by UziTech** [comment]
If you want to create a PR that adds the types we could add it
