### ISSUE TITLE
How to use from CLI in bash script?

### ISSUE THREAD

**Issue by dschach** [markedjs/marked-gfm-heading-id#411]
I use marked to convert markdown to html, and I want to use this plugin, but I don't see how to install or invoke it from the bash script.

I can install it as a dev-dependency, but then I get stuck, as I'd like to use a JSON config file.

Can you please provide some documentation for that? Thanks!

**Comment by UziTech** [comment]
There is no way to use extensions in marked with a JSON config file. You will have to use a .js config file with something like

```
// ~/.marked/index.js

import { gfmHeadingId } from "marked-gfm-heading-id";

export function(marked) {
  marked.use(gfmHeadingId());
}
```
